### ISSUE TITLE
Upgrade to latest gradle

### ISSUE THREAD

**Issue by 0xdevalias** [vmware/burp-rest-api#31] opened 2018-03-14 02:45 UTC
Currently the wrapper is set to build with `2.13` (Apr 25, 2016):

* https://github.com/vmware/burp-rest-api/blob/master/gradle/wrapper/gradle-wrapper.properties#L6

The latest version appears to be `4.6` (Feb 28, 2018):

* https://gradle.org/releases/

**Comment by gangelino** [comment] 2018-06-12 20:15
Dupe of #37, feel free to submit a PR! :)

**Closed** 2018-06-12 20:15 UTC
